version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    networks:
      - tasknet

  app:
    build: .
    container_name: task-manager-node
    restart: always
    ports:
      - "5002:5001"  # host:container
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - tasknet

networks:
  tasknet:
