apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc           # Name of the PVC for MariaDB data
  namespace: task-manager     # Namespace where PVC will be created
  labels:
    app: mariadb             # Label to identify this PVC belongs to MariaDB
    name: mariadb-pvc        # Additional label for PVC identification
spec:
  accessModes:
    - ReadWriteOnce         # Allows the volume to be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi          # Requesting 1 Gigabyte of storage space 