apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: task-manager
  labels:
    app: mariadb
type: Opaque
data:
  # The passwords should be base64 encoded
  # echo -n "devpass" | base64
  MYSQL_ROOT_PASSWORD: ZGV2cGFzcw==
  MYSQL_PASSWORD: ZGV2cGFzcw== 