apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
  labels:
    app: task-manager-api
data:
  DB_HOST: "db"
  DB_NAME: "taskdb"
  DB_USER: "devuser"
  PORT: "5002" 