apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: task-manager
  labels:
    app: task-manager-api
type: Opaque
data:
  # The password should be base64 encoded
  # echo -n "devpass" | base64
  DB_PASSWORD: ZGV2cGFzcw== 